### ISSUE TITLE
`.btn-danger` needs text color specified

### ISSUE THREAD

**Issue by rthrash** [PullJosh/lightbox#1]
Currently, too low contrast:
<img width="289" alt="admin - modx community 2018-10-18 11-23-38" src="https://user-images.githubusercontent.com/234237/47169254-9e8af880-d2c8-11e8-8b44-d6ff9da99ea9.png">

<img width="263" alt="admin - modx community 2018-10-18 11-26-46" src="https://user-images.githubusercontent.com/234237/47169289-b82c4000-d2c8-11e8-8d1a-acf40f1814ba.png">

Quick fix: add `color: #fff` to `.btn-danger`.

**Comment by PullJosh** [comment]
That was a good call! Thanks.
